import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';
import 'dotenv/config';
import { Pool } from 'pg';

const adapter = new PrismaPg(
    new Pool({
        connectionString: process.env.DATABASE_URL,
    }),
);
const prisma = new PrismaClient({ adapter });

const categories = [
    {
        code: 'VERTICAL_MONUMENT',
        name: 'Вертикальные стелы',
        sortOrder: 10,
    },
    {
        code: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальные стелы',
        sortOrder: 20,
    },
    {
        code: 'CROSS',
        name: 'Кресты',
        sortOrder: 30,
    },
    {
        code: 'TABLES_AND_CHAIRS',
        name: 'Столы и лавки',
        sortOrder: 40,
    },
    {
        code: 'FENCES',
        name: 'Ограды',
        sortOrder: 50,
    },
    {
        code: 'VASES',
        name: 'Вазы',
        sortOrder: 60,
    },
    {
        code: 'BALLS',
        name: 'Шары',
        sortOrder: 70,
    },
    {
        code: 'COFFIN',
        name: 'Гробы',
        sortOrder: 80,
    },
    {
        code: 'WREATHS',
        name: 'Венки',
        sortOrder: 90,
    },
    {
        code: 'BASKETS',
        name: 'Корзины',
        sortOrder: 100,
    },
];

const products = [
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-1',
        imageKey: 'products/vertical-monument/products-1.webp',
        sortOrder: 10,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-2',
        imageKey: 'products/vertical-monument/products-2.webp',
        sortOrder: 20,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-3',
        imageKey: 'products/vertical-monument/products-3.webp',
        sortOrder: 30,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-4',
        imageKey: 'products/vertical-monument/products-4.webp',
        sortOrder: 40,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-5',
        imageKey: 'products/vertical-monument/products-5.webp',
        sortOrder: 50,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-6',
        imageKey: 'products/vertical-monument/products-6.webp',
        sortOrder: 60,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-7',
        imageKey: 'products/vertical-monument/products-7.webp',
        sortOrder: 70,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-8',
        imageKey: 'products/vertical-monument/products-8.webp',
        sortOrder: 80,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-9',
        imageKey: 'products/vertical-monument/products-9.webp',
        sortOrder: 90,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-10',
        imageKey: 'products/vertical-monument/products-10.webp',
        sortOrder: 100,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-11',
        imageKey: 'products/vertical-monument/products-11.webp',
        sortOrder: 110,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-12',
        imageKey: 'products/vertical-monument/products-12.webp',
        sortOrder: 120,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-13',
        imageKey: 'products/vertical-monument/products-13.webp',
        sortOrder: 130,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-14',
        imageKey: 'products/vertical-monument/products-14.webp',
        sortOrder: 140,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-15',
        imageKey: 'products/vertical-monument/products-15.webp',
        sortOrder: 150,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-16',
        imageKey: 'products/vertical-monument/products-16.webp',
        sortOrder: 160,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-17',
        imageKey: 'products/vertical-monument/products-17.webp',
        sortOrder: 170,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-18',
        imageKey: 'products/vertical-monument/products-18.webp',
        sortOrder: 180,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-19',
        imageKey: 'products/vertical-monument/products-19.webp',
        sortOrder: 190,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-20',
        imageKey: 'products/vertical-monument/products-20.webp',
        sortOrder: 200,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-21',
        imageKey: 'products/vertical-monument/products-21.webp',
        sortOrder: 210,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-22',
        imageKey: 'products/vertical-monument/products-22.webp',
        sortOrder: 220,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-23',
        imageKey: 'products/vertical-monument/products-23.webp',
        sortOrder: 230,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-24',
        imageKey: 'products/vertical-monument/products-24.webp',
        sortOrder: 240,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-25',
        imageKey: 'products/vertical-monument/products-25.webp',
        sortOrder: 250,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-26',
        imageKey: 'products/vertical-monument/products-26.webp',
        sortOrder: 260,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-27',
        imageKey: 'products/vertical-monument/products-27.webp',
        sortOrder: 270,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-28',
        imageKey: 'products/vertical-monument/products-28.webp',
        sortOrder: 280,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-29',
        imageKey: 'products/vertical-monument/products-29.webp',
        sortOrder: 290,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-30',
        imageKey: 'products/vertical-monument/products-30.webp',
        sortOrder: 300,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-31',
        imageKey: 'products/vertical-monument/products-31.webp',
        sortOrder: 310,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-32',
        imageKey: 'products/vertical-monument/products-32.webp',
        sortOrder: 320,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-33',
        imageKey: 'products/vertical-monument/products-33.webp',
        sortOrder: 330,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-34',
        imageKey: 'products/vertical-monument/products-34.webp',
        sortOrder: 340,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-35',
        imageKey: 'products/vertical-monument/products-35.webp',
        sortOrder: 350,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-36',
        imageKey: 'products/vertical-monument/products-36.webp',
        sortOrder: 360,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-37',
        imageKey: 'products/vertical-monument/products-37.webp',
        sortOrder: 370,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-38',
        imageKey: 'products/vertical-monument/products-38.webp',
        sortOrder: 380,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-39',
        imageKey: 'products/vertical-monument/products-39.webp',
        sortOrder: 390,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-40',
        imageKey: 'products/vertical-monument/products-40.webp',
        sortOrder: 400,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-41',
        imageKey: 'products/vertical-monument/products-41.webp',
        sortOrder: 410,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-42',
        imageKey: 'products/vertical-monument/products-42.webp',
        sortOrder: 420,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-43',
        imageKey: 'products/vertical-monument/products-43.webp',
        sortOrder: 430,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-44',
        imageKey: 'products/vertical-monument/products-44.webp',
        sortOrder: 440,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-45',
        imageKey: 'products/vertical-monument/products-45.webp',
        sortOrder: 450,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-46',
        imageKey: 'products/vertical-monument/products-46.webp',
        sortOrder: 460,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-47',
        imageKey: 'products/vertical-monument/products-47.webp',
        sortOrder: 470,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-48',
        imageKey: 'products/vertical-monument/products-48.webp',
        sortOrder: 480,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-49',
        imageKey: 'products/vertical-monument/products-49.webp',
        sortOrder: 490,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-50',
        imageKey: 'products/vertical-monument/products-50.webp',
        sortOrder: 500,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-51',
        imageKey: 'products/vertical-monument/products-51.webp',
        sortOrder: 510,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-52',
        imageKey: 'products/vertical-monument/products-52.webp',
        sortOrder: 520,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-53',
        imageKey: 'products/vertical-monument/products-53.webp',
        sortOrder: 530,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-54',
        imageKey: 'products/vertical-monument/products-54.webp',
        sortOrder: 540,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-55',
        imageKey: 'products/vertical-monument/products-55.webp',
        sortOrder: 550,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-56',
        imageKey: 'products/vertical-monument/products-56.webp',
        sortOrder: 560,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-57',
        imageKey: 'products/vertical-monument/products-57.webp',
        sortOrder: 570,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-58',
        imageKey: 'products/vertical-monument/products-58.webp',
        sortOrder: 580,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-59',
        imageKey: 'products/vertical-monument/products-59.webp',
        sortOrder: 590,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-60',
        imageKey: 'products/vertical-monument/products-60.webp',
        sortOrder: 600,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-61',
        imageKey: 'products/vertical-monument/products-61.webp',
        sortOrder: 610,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-62',
        imageKey: 'products/vertical-monument/products-62.webp',
        sortOrder: 620,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-63',
        imageKey: 'products/vertical-monument/products-63.webp',
        sortOrder: 630,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-64',
        imageKey: 'products/vertical-monument/products-64.webp',
        sortOrder: 640,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-65',
        imageKey: 'products/vertical-monument/products-65.webp',
        sortOrder: 650,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-66',
        imageKey: 'products/vertical-monument/products-66.webp',
        sortOrder: 660,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-67',
        imageKey: 'products/vertical-monument/products-67.webp',
        sortOrder: 670,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-68',
        imageKey: 'products/vertical-monument/products-68.webp',
        sortOrder: 680,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-69',
        imageKey: 'products/vertical-monument/products-69.webp',
        sortOrder: 690,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-70',
        imageKey: 'products/vertical-monument/products-70.webp',
        sortOrder: 700,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-71',
        imageKey: 'products/vertical-monument/products-71.webp',
        sortOrder: 710,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-72',
        imageKey: 'products/vertical-monument/products-72.webp',
        sortOrder: 720,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-73',
        imageKey: 'products/vertical-monument/products-73.webp',
        sortOrder: 730,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-74',
        imageKey: 'products/vertical-monument/products-74.webp',
        sortOrder: 740,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-75',
        imageKey: 'products/vertical-monument/products-75.webp',
        sortOrder: 750,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-76',
        imageKey: 'products/vertical-monument/products-76.webp',
        sortOrder: 760,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-77',
        imageKey: 'products/vertical-monument/products-77.webp',
        sortOrder: 770,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-78',
        imageKey: 'products/vertical-monument/products-78.webp',
        sortOrder: 780,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-79',
        imageKey: 'products/vertical-monument/products-79.webp',
        sortOrder: 790,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-80',
        imageKey: 'products/vertical-monument/products-80.webp',
        sortOrder: 800,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-81',
        imageKey: 'products/vertical-monument/products-81.webp',
        sortOrder: 810,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-82',
        imageKey: 'products/vertical-monument/products-82.webp',
        sortOrder: 820,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-83',
        imageKey: 'products/vertical-monument/products-83.webp',
        sortOrder: 830,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-84',
        imageKey: 'products/vertical-monument/products-84.webp',
        sortOrder: 840,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-85',
        imageKey: 'products/vertical-monument/products-85.webp',
        sortOrder: 850,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-86',
        imageKey: 'products/vertical-monument/products-86.webp',
        sortOrder: 860,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-87',
        imageKey: 'products/vertical-monument/products-87.webp',
        sortOrder: 870,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-88',
        imageKey: 'products/vertical-monument/products-88.webp',
        sortOrder: 880,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-89',
        imageKey: 'products/vertical-monument/products-89.webp',
        sortOrder: 890,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-90',
        imageKey: 'products/vertical-monument/products-90.webp',
        sortOrder: 900,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-91',
        imageKey: 'products/vertical-monument/products-91.webp',
        sortOrder: 910,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-92',
        imageKey: 'products/vertical-monument/products-92.webp',
        sortOrder: 920,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-93',
        imageKey: 'products/vertical-monument/products-93.webp',
        sortOrder: 930,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-94',
        imageKey: 'products/vertical-monument/products-94.webp',
        sortOrder: 940,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-95',
        imageKey: 'products/vertical-monument/products-95.webp',
        sortOrder: 950,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-96',
        imageKey: 'products/vertical-monument/products-96.webp',
        sortOrder: 960,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-97',
        imageKey: 'products/vertical-monument/products-97.webp',
        sortOrder: 970,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-98',
        imageKey: 'products/vertical-monument/products-98.webp',
        sortOrder: 980,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-99',
        imageKey: 'products/vertical-monument/products-99.webp',
        sortOrder: 990,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-100',
        imageKey: 'products/vertical-monument/products-100.webp',
        sortOrder: 1000,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-101',
        imageKey: 'products/vertical-monument/products-101.webp',
        sortOrder: 1010,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-102',
        imageKey: 'products/vertical-monument/products-102.webp',
        sortOrder: 1020,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-103',
        imageKey: 'products/vertical-monument/products-103.webp',
        sortOrder: 1030,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-104',
        imageKey: 'products/vertical-monument/products-104.webp',
        sortOrder: 1040,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-105',
        imageKey: 'products/vertical-monument/products-105.webp',
        sortOrder: 1050,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-106',
        imageKey: 'products/vertical-monument/products-106.webp',
        sortOrder: 1060,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-107',
        imageKey: 'products/vertical-monument/products-107.webp',
        sortOrder: 1070,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-108',
        imageKey: 'products/vertical-monument/products-108.webp',
        sortOrder: 1080,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-109',
        imageKey: 'products/vertical-monument/products-109.webp',
        sortOrder: 1090,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-110',
        imageKey: 'products/vertical-monument/products-110.webp',
        sortOrder: 1100,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-111',
        imageKey: 'products/vertical-monument/products-111.webp',
        sortOrder: 1110,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-112',
        imageKey: 'products/vertical-monument/products-112.webp',
        sortOrder: 1120,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-113',
        imageKey: 'products/vertical-monument/products-113.webp',
        sortOrder: 1130,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-114',
        imageKey: 'products/vertical-monument/products-114.webp',
        sortOrder: 1140,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-115',
        imageKey: 'products/vertical-monument/products-115.webp',
        sortOrder: 1150,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-116',
        imageKey: 'products/vertical-monument/products-116.webp',
        sortOrder: 1160,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-117',
        imageKey: 'products/vertical-monument/products-117.webp',
        sortOrder: 1170,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-118',
        imageKey: 'products/vertical-monument/products-118.webp',
        sortOrder: 1180,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-119',
        imageKey: 'products/vertical-monument/products-119.webp',
        sortOrder: 1190,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-120',
        imageKey: 'products/vertical-monument/products-120.webp',
        sortOrder: 1200,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-121',
        imageKey: 'products/vertical-monument/products-121.webp',
        sortOrder: 1210,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-122',
        imageKey: 'products/vertical-monument/products-122.webp',
        sortOrder: 1220,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-123',
        imageKey: 'products/vertical-monument/products-123.webp',
        sortOrder: 1230,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-124',
        imageKey: 'products/vertical-monument/products-124.webp',
        sortOrder: 1240,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-125',
        imageKey: 'products/vertical-monument/products-125.webp',
        sortOrder: 1250,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-126',
        imageKey: 'products/vertical-monument/products-126.webp',
        sortOrder: 1260,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-127',
        imageKey: 'products/vertical-monument/products-127.webp',
        sortOrder: 1270,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-128',
        imageKey: 'products/vertical-monument/products-128.webp',
        sortOrder: 1280,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-129',
        imageKey: 'products/vertical-monument/products-129.webp',
        sortOrder: 1290,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-130',
        imageKey: 'products/vertical-monument/products-130.webp',
        sortOrder: 1300,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-131',
        imageKey: 'products/vertical-monument/products-131.webp',
        sortOrder: 1310,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела А-132',
        imageKey: 'products/vertical-monument/products-132.webp',
        sortOrder: 1320,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-1',
        imageKey: 'products/vertical-monument/products-133.webp',
        sortOrder: 1330,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-2',
        imageKey: 'products/vertical-monument/products-134.webp',
        sortOrder: 1340,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-3',
        imageKey: 'products/vertical-monument/products-135.webp',
        sortOrder: 1350,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-4',
        imageKey: 'products/vertical-monument/products-136.webp',
        sortOrder: 1360,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-5',
        imageKey: 'products/vertical-monument/products-137.webp',
        sortOrder: 1370,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-6',
        imageKey: 'products/vertical-monument/products-138.webp',
        sortOrder: 1380,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-7',
        imageKey: 'products/vertical-monument/products-139.webp',
        sortOrder: 1390,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-8',
        imageKey: 'products/vertical-monument/products-140.webp',
        sortOrder: 1400,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-9',
        imageKey: 'products/vertical-monument/products-141.webp',
        sortOrder: 1410,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-10',
        imageKey: 'products/vertical-monument/products-142.webp',
        sortOrder: 1420,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-11',
        imageKey: 'products/vertical-monument/products-143.webp',
        sortOrder: 1430,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-12',
        imageKey: 'products/vertical-monument/products-144.webp',
        sortOrder: 1440,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-13',
        imageKey: 'products/vertical-monument/products-145.webp',
        sortOrder: 1450,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-14',
        imageKey: 'products/vertical-monument/products-146.webp',
        sortOrder: 1460,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-15',
        imageKey: 'products/vertical-monument/products-147.webp',
        sortOrder: 1470,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-16',
        imageKey: 'products/vertical-monument/products-148.webp',
        sortOrder: 1480,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-17',
        imageKey: 'products/vertical-monument/products-149.webp',
        sortOrder: 1490,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-18',
        imageKey: 'products/vertical-monument/products-150.webp',
        sortOrder: 1500,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела Б-19',
        imageKey: 'products/vertical-monument/products-151.webp',
        sortOrder: 1510,
    },
    {
        categoryCode: 'VERTICAL_MONUMENT',
        name: 'Вертикальная стела В-1',
        imageKey: 'products/vertical-monument/products-152.webp',
        sortOrder: 1520,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-1',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-1.webp',
        sortOrder: 10,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-2',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-2.webp',
        sortOrder: 20,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-3',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-3.webp',
        sortOrder: 30,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-4',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-4.webp',
        sortOrder: 40,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-5',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-5.webp',
        sortOrder: 50,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-6',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-6.webp',
        sortOrder: 60,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-7',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-7.webp',
        sortOrder: 70,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-8',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-8.webp',
        sortOrder: 80,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-9',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-9.webp',
        sortOrder: 90,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-10',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-10.webp',
        sortOrder: 100,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-11',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-11.webp',
        sortOrder: 110,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-12',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-12.webp',
        sortOrder: 120,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-13',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-13.webp',
        sortOrder: 130,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-14',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-14.webp',
        sortOrder: 140,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-15',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-15.webp',
        sortOrder: 150,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-16',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-16.webp',
        sortOrder: 160,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-17',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-17.webp',
        sortOrder: 170,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-18',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-18.webp',
        sortOrder: 180,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-19',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-19.webp',
        sortOrder: 190,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-20',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-20.webp',
        sortOrder: 200,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-21',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-21.webp',
        sortOrder: 210,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-22',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-22.webp',
        sortOrder: 220,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-23',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-23.webp',
        sortOrder: 230,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-24',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-24.webp',
        sortOrder: 240,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-25',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-25.webp',
        sortOrder: 250,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-26',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-26.webp',
        sortOrder: 260,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-27',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-27.webp',
        sortOrder: 270,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-28',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-28.webp',
        sortOrder: 280,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела А-29',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-29.webp',
        sortOrder: 290,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела Б-1',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-30.webp',
        sortOrder: 300,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела Б-2',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-31.webp',
        sortOrder: 310,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела Б-3',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-32.webp',
        sortOrder: 320,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела Б-4',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-33.webp',
        sortOrder: 330,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела Б-5',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-34.webp',
        sortOrder: 340,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела Б-6',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-35.webp',
        sortOrder: 350,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела Б-7',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-36.webp',
        sortOrder: 360,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела Б-8',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-37.webp',
        sortOrder: 370,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела Б-9',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-38.webp',
        sortOrder: 380,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела Б-10',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-39.webp',
        sortOrder: 390,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела Б-11',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-40.webp',
        sortOrder: 400,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела Б-12',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-41.webp',
        sortOrder: 410,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела Б-13',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-42.webp',
        sortOrder: 420,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела Б-14',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-43.webp',
        sortOrder: 430,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела Б-15',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-44.webp',
        sortOrder: 440,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела Б-16',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-45.webp',
        sortOrder: 450,
    },
    {
        categoryCode: 'HORIZONTAL_MONUMENT',
        name: 'Горизонтальная стела В-1',
        imageKey: 'products/horizontal-monument/horizontal-monument-products-46.webp',
        sortOrder: 460,
    },
    {
        categoryCode: 'CROSS',
        name: 'Крест А-1',
        imageKey: 'products/cross/cross-products-1.webp',
        sortOrder: 10,
    },
    {
        categoryCode: 'CROSS',
        name: 'Крест Б-1',
        imageKey: 'products/cross/cross-products-2.webp',
        sortOrder: 20,
    },
    {
        categoryCode: 'CROSS',
        name: 'Крест Б-2',
        imageKey: 'products/cross/cross-products-3.webp',
        sortOrder: 30,
    },
    {
        categoryCode: 'CROSS',
        name: 'Крест Б-3',
        imageKey: 'products/cross/cross-products-4.webp',
        sortOrder: 40,
    },
    {
        categoryCode: 'CROSS',
        name: 'Крест Б-4',
        imageKey: 'products/cross/cross-products-5.webp',
        sortOrder: 50,
    },
    {
        categoryCode: 'CROSS',
        name: 'Крест Б-5',
        imageKey: 'products/cross/cross-products-6.webp',
        sortOrder: 60,
    },
    {
        categoryCode: 'TABLES_AND_CHAIRS',
        name: 'Стол и лавка А-1',
        imageKey: 'products/tables-and-chairs/tables-and-chairs-products-1.webp',
        sortOrder: 10,
    },
    {
        categoryCode: 'FENCES',
        name: 'Ограда А-1',
        imageKey: 'products/fences/fences-products-1.webp',
        sortOrder: 10,
    },
    {
        categoryCode: 'FENCES',
        name: 'Ограда А-2',
        imageKey: 'products/fences/fences-products-2.webp',
        sortOrder: 20,
    },
    {
        categoryCode: 'VASES',
        name: 'Ваза А-1',
        imageKey: 'products/vases/vases-products-1.webp',
        sortOrder: 10,
    },
    {
        categoryCode: 'VASES',
        name: 'Ваза А-2',
        imageKey: 'products/vases/vases-products-2.webp',
        sortOrder: 20,
    },
    {
        categoryCode: 'VASES',
        name: 'Ваза А-3',
        imageKey: 'products/vases/vases-products-3.webp',
        sortOrder: 30,
    },
    {
        categoryCode: 'VASES',
        name: 'Ваза А-4',
        imageKey: 'products/vases/vases-products-4.webp',
        sortOrder: 40,
    },
    {
        categoryCode: 'VASES',
        name: 'Ваза А-5',
        imageKey: 'products/vases/vases-products-5.webp',
        sortOrder: 50,
    },
    {
        categoryCode: 'VASES',
        name: 'Ваза А-6',
        imageKey: 'products/vases/vases-products-6.webp',
        sortOrder: 60,
    },
    {
        categoryCode: 'VASES',
        name: 'Ваза А-7',
        imageKey: 'products/vases/vases-products-7.webp',
        sortOrder: 70,
    },
    {
        categoryCode: 'VASES',
        name: 'Ваза А-8',
        imageKey: 'products/vases/vases-products-8.webp',
        sortOrder: 80,
    },
    {
        categoryCode: 'VASES',
        name: 'Ваза А-9',
        imageKey: 'products/vases/vases-products-9.webp',
        sortOrder: 90,
    },
    {
        categoryCode: 'VASES',
        name: 'Ваза А-10',
        imageKey: 'products/vases/vases-products-10.webp',
        sortOrder: 100,
    },
    {
        categoryCode: 'BALLS',
        name: 'Шар А-1',
        imageKey: 'products/balls/balls-products-1.webp',
        sortOrder: 10,
    },
    {
        categoryCode: 'BALLS',
        name: 'Шар А-2',
        imageKey: 'products/balls/balls-products-2.webp',
        sortOrder: 20,
    },
    {
        categoryCode: 'BALLS',
        name: 'Шар А-3',
        imageKey: 'products/balls/balls-products-3.webp',
        sortOrder: 30,
    },
    {
        categoryCode: 'BALLS',
        name: 'Шар А-4',
        imageKey: 'products/balls/balls-products-4.webp',
        sortOrder: 40,
    },
    {
        categoryCode: 'BALLS',
        name: 'Шар А-5',
        imageKey: 'products/balls/balls-products-5.webp',
        sortOrder: 50,
    },
    {
        categoryCode: 'BALLS',
        name: 'Шар А-6',
        imageKey: 'products/balls/balls-products-6.webp',
        sortOrder: 60,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-1',
        imageKey: 'products/coffin/coffin-products-1.webp',
        sortOrder: 10,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-2',
        imageKey: 'products/coffin/coffin-products-2.webp',
        sortOrder: 20,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-3',
        imageKey: 'products/coffin/coffin-products-3.webp',
        sortOrder: 30,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-4',
        imageKey: 'products/coffin/coffin-products-4.webp',
        sortOrder: 40,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-5',
        imageKey: 'products/coffin/coffin-products-5.webp',
        sortOrder: 50,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-6',
        imageKey: 'products/coffin/coffin-products-6.webp',
        sortOrder: 60,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-7',
        imageKey: 'products/coffin/coffin-products-7.webp',
        sortOrder: 70,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-8',
        imageKey: 'products/coffin/coffin-products-8.webp',
        sortOrder: 80,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-9',
        imageKey: 'products/coffin/coffin-products-9.webp',
        sortOrder: 90,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-10',
        imageKey: 'products/coffin/coffin-products-10.webp',
        sortOrder: 100,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-11',
        imageKey: 'products/coffin/coffin-products-11.webp',
        sortOrder: 110,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-12',
        imageKey: 'products/coffin/coffin-products-12.webp',
        sortOrder: 120,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-13',
        imageKey: 'products/coffin/coffin-products-13.webp',
        sortOrder: 130,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-14',
        imageKey: 'products/coffin/coffin-products-14.webp',
        sortOrder: 140,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-15',
        imageKey: 'products/coffin/coffin-products-15.webp',
        sortOrder: 150,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-16',
        imageKey: 'products/coffin/coffin-products-16.webp',
        sortOrder: 160,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-17',
        imageKey: 'products/coffin/coffin-products-17.webp',
        sortOrder: 170,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-18',
        imageKey: 'products/coffin/coffin-products-18.webp',
        sortOrder: 180,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-19',
        imageKey: 'products/coffin/coffin-products-19.webp',
        sortOrder: 190,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-20',
        imageKey: 'products/coffin/coffin-products-20.webp',
        sortOrder: 200,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-21',
        imageKey: 'products/coffin/coffin-products-21.webp',
        sortOrder: 210,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-22',
        imageKey: 'products/coffin/coffin-products-22.webp',
        sortOrder: 220,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-23',
        imageKey: 'products/coffin/coffin-products-23.webp',
        sortOrder: 230,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-24',
        imageKey: 'products/coffin/coffin-products-24.webp',
        sortOrder: 240,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-25',
        imageKey: 'products/coffin/coffin-products-25.webp',
        sortOrder: 250,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-26',
        imageKey: 'products/coffin/coffin-products-26.webp',
        sortOrder: 260,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-27',
        imageKey: 'products/coffin/coffin-products-27.webp',
        sortOrder: 270,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-28',
        imageKey: 'products/coffin/coffin-products-28.webp',
        sortOrder: 280,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-29',
        imageKey: 'products/coffin/coffin-products-29.webp',
        sortOrder: 290,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-30',
        imageKey: 'products/coffin/coffin-products-30.webp',
        sortOrder: 300,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-31',
        imageKey: 'products/coffin/coffin-products-31.webp',
        sortOrder: 310,
    },
    {
        categoryCode: 'COFFIN',
        name: 'Гроб А-32',
        imageKey: 'products/coffin/coffin-products-32.webp',
        sortOrder: 320,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-1',
        imageKey: 'products/wreaths/wreaths-products-1.webp',
        sortOrder: 10,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-2',
        imageKey: 'products/wreaths/wreaths-products-2.webp',
        sortOrder: 20,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-3',
        imageKey: 'products/wreaths/wreaths-products-3.webp',
        sortOrder: 30,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-4',
        imageKey: 'products/wreaths/wreaths-products-4.webp',
        sortOrder: 40,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-5',
        imageKey: 'products/wreaths/wreaths-products-5.webp',
        sortOrder: 50,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-6',
        imageKey: 'products/wreaths/wreaths-products-6.webp',
        sortOrder: 60,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-7',
        imageKey: 'products/wreaths/wreaths-products-7.webp',
        sortOrder: 70,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-8',
        imageKey: 'products/wreaths/wreaths-products-8.webp',
        sortOrder: 80,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-9',
        imageKey: 'products/wreaths/wreaths-products-9.webp',
        sortOrder: 90,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-10',
        imageKey: 'products/wreaths/wreaths-products-10.webp',
        sortOrder: 100,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-11',
        imageKey: 'products/wreaths/wreaths-products-11.webp',
        sortOrder: 110,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-12',
        imageKey: 'products/wreaths/wreaths-products-12.webp',
        sortOrder: 120,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-13',
        imageKey: 'products/wreaths/wreaths-products-13.webp',
        sortOrder: 130,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-14',
        imageKey: 'products/wreaths/wreaths-products-14.webp',
        sortOrder: 140,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-15',
        imageKey: 'products/wreaths/wreaths-products-15.webp',
        sortOrder: 150,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-16',
        imageKey: 'products/wreaths/wreaths-products-16.webp',
        sortOrder: 160,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-17',
        imageKey: 'products/wreaths/wreaths-products-17.webp',
        sortOrder: 170,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-18',
        imageKey: 'products/wreaths/wreaths-products-18.webp',
        sortOrder: 180,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-19',
        imageKey: 'products/wreaths/wreaths-products-19.webp',
        sortOrder: 190,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-20',
        imageKey: 'products/wreaths/wreaths-products-20.webp',
        sortOrder: 200,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-21',
        imageKey: 'products/wreaths/wreaths-products-21.webp',
        sortOrder: 210,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-22',
        imageKey: 'products/wreaths/wreaths-products-22.webp',
        sortOrder: 220,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-23',
        imageKey: 'products/wreaths/wreaths-products-23.webp',
        sortOrder: 230,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-24',
        imageKey: 'products/wreaths/wreaths-products-24.webp',
        sortOrder: 240,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-25',
        imageKey: 'products/wreaths/wreaths-products-25.webp',
        sortOrder: 250,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-26',
        imageKey: 'products/wreaths/wreaths-products-26.webp',
        sortOrder: 260,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-27',
        imageKey: 'products/wreaths/wreaths-products-27.webp',
        sortOrder: 270,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-28',
        imageKey: 'products/wreaths/wreaths-products-28.webp',
        sortOrder: 280,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-29',
        imageKey: 'products/wreaths/wreaths-products-29.webp',
        sortOrder: 290,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-30',
        imageKey: 'products/wreaths/wreaths-products-30.webp',
        sortOrder: 300,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-31',
        imageKey: 'products/wreaths/wreaths-products-31.webp',
        sortOrder: 310,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-32',
        imageKey: 'products/wreaths/wreaths-products-32.webp',
        sortOrder: 320,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-33',
        imageKey: 'products/wreaths/wreaths-products-33.webp',
        sortOrder: 330,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-34',
        imageKey: 'products/wreaths/wreaths-products-34.webp',
        sortOrder: 340,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-35',
        imageKey: 'products/wreaths/wreaths-products-35.webp',
        sortOrder: 350,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-36',
        imageKey: 'products/wreaths/wreaths-products-36.webp',
        sortOrder: 360,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-37',
        imageKey: 'products/wreaths/wreaths-products-37.webp',
        sortOrder: 370,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-38',
        imageKey: 'products/wreaths/wreaths-products-38.webp',
        sortOrder: 380,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-39',
        imageKey: 'products/wreaths/wreaths-products-39.webp',
        sortOrder: 390,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-40',
        imageKey: 'products/wreaths/wreaths-products-40.webp',
        sortOrder: 400,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-41',
        imageKey: 'products/wreaths/wreaths-products-41.webp',
        sortOrder: 410,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-42',
        imageKey: 'products/wreaths/wreaths-products-42.webp',
        sortOrder: 420,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-43',
        imageKey: 'products/wreaths/wreaths-products-43.webp',
        sortOrder: 430,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-44',
        imageKey: 'products/wreaths/wreaths-products-44.webp',
        sortOrder: 440,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-45',
        imageKey: 'products/wreaths/wreaths-products-45.webp',
        sortOrder: 450,
    },
    {
        categoryCode: 'WREATHS',
        name: 'Венок А-46',
        imageKey: 'products/wreaths/wreaths-products-46.webp',
        sortOrder: 460,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-1',
        imageKey: 'products/baskets/baskets-products-1.webp',
        sortOrder: 10,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-2',
        imageKey: 'products/baskets/baskets-products-2.webp',
        sortOrder: 20,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-3',
        imageKey: 'products/baskets/baskets-products-3.webp',
        sortOrder: 30,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-4',
        imageKey: 'products/baskets/baskets-products-4.webp',
        sortOrder: 40,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-5',
        imageKey: 'products/baskets/baskets-products-5.webp',
        sortOrder: 50,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-6',
        imageKey: 'products/baskets/baskets-products-6.webp',
        sortOrder: 60,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-7',
        imageKey: 'products/baskets/baskets-products-7.webp',
        sortOrder: 70,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-8',
        imageKey: 'products/baskets/baskets-products-8.webp',
        sortOrder: 80,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-9',
        imageKey: 'products/baskets/baskets-products-9.webp',
        sortOrder: 90,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-10',
        imageKey: 'products/baskets/baskets-products-10.webp',
        sortOrder: 100,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-11',
        imageKey: 'products/baskets/baskets-products-11.webp',
        sortOrder: 110,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-12',
        imageKey: 'products/baskets/baskets-products-12.webp',
        sortOrder: 120,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-13',
        imageKey: 'products/baskets/baskets-products-13.webp',
        sortOrder: 130,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-14',
        imageKey: 'products/baskets/baskets-products-14.webp',
        sortOrder: 140,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-15',
        imageKey: 'products/baskets/baskets-products-15.webp',
        sortOrder: 150,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-16',
        imageKey: 'products/baskets/baskets-products-16.webp',
        sortOrder: 160,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-17',
        imageKey: 'products/baskets/baskets-products-17.webp',
        sortOrder: 170,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-18',
        imageKey: 'products/baskets/baskets-products-18.webp',
        sortOrder: 180,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-19',
        imageKey: 'products/baskets/baskets-products-19.webp',
        sortOrder: 190,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-20',
        imageKey: 'products/baskets/baskets-products-20.webp',
        sortOrder: 200,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-21',
        imageKey: 'products/baskets/baskets-products-21.webp',
        sortOrder: 210,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-22',
        imageKey: 'products/baskets/baskets-products-22.webp',
        sortOrder: 220,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-23',
        imageKey: 'products/baskets/baskets-products-23.webp',
        sortOrder: 230,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-24',
        imageKey: 'products/baskets/baskets-products-24.webp',
        sortOrder: 240,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-25',
        imageKey: 'products/baskets/baskets-products-25.webp',
        sortOrder: 250,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-26',
        imageKey: 'products/baskets/baskets-products-26.webp',
        sortOrder: 260,
    },
    {
        categoryCode: 'BASKETS',
        name: 'Корзина А-27',
        imageKey: 'products/baskets/baskets-products-27.webp',
        sortOrder: 270,
    },
];

const seed = async () => {
    for (const category of categories) {
        await prisma.productCategory.upsert({
            where: {
                code: category.code,
            },
            update: {
                name: category.name,
                sortOrder: category.sortOrder,
            },
            create: category,
        });
    }

    for (const product of products) {
        const category = await prisma.productCategory.findUniqueOrThrow({
            where: {
                code: product.categoryCode,
            },
        });

        await prisma.product.upsert({
            where: {
                imageKey: product.imageKey,
            },
            update: {
                name: product.name,
                sortOrder: product.sortOrder,
                categoryId: category.id,
            },
            create: {
                name: product.name,
                imageKey: product.imageKey,
                sortOrder: product.sortOrder,
                categoryId: category.id,
            },
        });
    }
};

seed()
    .then(async () => {
        await prisma.$disconnect();
    })
    .catch(async (error: unknown) => {
        console.error(error);
        await prisma.$disconnect();
        process.exit(1);
    });
